### ISSUE TITLE
Issue in this Codelabs doc 10 UI Testing

### ISSUE THREAD

**Issue by mengdd** [googlecodelabs/android-hilt#1]
On page: https://codelabs.developers.google.com/codelabs/android-hilt/#9

Currently, in the doc it's written:
```
android {
    ...
    defaultConfig {
        ...
        testInstrumentationRunner "com.example.android.dagger.CustomTestRunner"
    }
    ...
}
```

The correct one should be:
```
testInstrumentationRunner "com.example.android.hilt.CustomTestRunner"
```

Because the code using package name with `hilt`, not `dagger`.

**Comment by manuelvicnt** [comment]
Thank you for catching that! Already fixed the text in the codelab :) If you refresh, you should be able to see it! Thank you
