### ISSUE TITLE
Dependency injection with Hilt is adding WRITE_EXTERNAL_STORAGE and READ_PHONE_STATE permissions automatically for app

### ISSUE THREAD

**Issue by nvquangth** [googlecodelabs/android-hilt#11]
After I added Hilt dependency for my app follow by [guide][1] with latest version **2.28-alpha**

```
// build.gradle

buildscript {
    ...
    dependencies {
        ...
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.28-alpha'
    }
}
```

```
// app/build.gradle

...
apply plugin: 'kotlin-kapt'
apply plugin: 'dagger.hilt.android.plugin'

android {
    ...
}

dependencies {
    implementation "com.google.dagger:hilt-android:2.28-alpha"
    kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
}
```

I realize that my app added WRITE_EXTERNAL_STORAGE and READ_PHONE_STATE permissions automatically.

I checked permissions by way: MyApp -> AppInfo -> Permissions

 - WRITE_EXTERNAL_STORAGE
 - READ_PHONE_STATE

Although, I have never request those permissions in Manifest.xml file or programmatically.

I try remove Hilt dependency and again check permissions. And I was not see them.

Is it a bug of Hilt? Anyone have the same problem?

  [1]: https://developer.android.com/training/dependency-injection/hilt-android#setup

**Comment by manuelvicnt** [comment]
That was a bug that's been solved in the last versions of Hilt. It shouldn't happen in version `2.29.1`

**Comment by nvquangth** [comment]
@manuelvicnt Thanks. updating to Hilt latest version solved the problem. (p/s: Hilt guide not update)
