### ISSUE TITLE
Any update for last 6 months?

### ISSUE THREAD

**Issue by peerless2012** [googlecodelabs/android-hilt#12]
I plan to use hilt in my new project, but this lib is still alpha and not update for 6 months, so is this lib not support or not?

**Comment by mdhishaamakhtar** [comment]
Yes it is supported. It is in beta now, See this: https://github.com/google/dagger/releases/tag/dagger-2.33

**Comment by peerless2012** [comment]
The [hilt dev](https://dagger.dev/hilt/gradle-setup) website is update too.

And I am happy that this component is still on work, thanks!
