### ISSUE TITLE
Injecting NavController into a composable

### ISSUE THREAD

**Issue by rupansh** [googlecodelabs/android-hilt#19]
Going to other routes from a composable requires a `NavController` object
There should be a way to inject this object (Possibly through ViewModel) as its very much a singleton dependency

**Comment by hongwei-bai** [comment]
same, I would rather not passing it through from the top level.

**Comment by manuelvicnt** [comment]
Please, feel free to add these feature requests to the Dagger/Hilt GH project (https://github.com/google/dagger/issues) instead of here. Thank you!
