### ISSUE TITLE
Cannot access HiltAndroidApp

### ISSUE THREAD

**Issue by hcknl** [googlecodelabs/android-hilt#22]
Hi,

After updating kotlin plugin from 1.4.32 to 202-1.5.10-release-894.AS8194.7 and Studio from 4.1.2 to 4.2.1, the builds are getting error: cannot access HiltAndroidApp 

@HiltAndroidApp
abstract class MyApplication : MultiDexApplication()

implementation "com.google.dagger:hilt-android:2:36"
kapt : com.google.dagger:hilt-compiler:2:36

I am now trying to figure it out what the problem is.

Thanks

**Comment by hcknl** [comment]
Changing implementation "com.googşe.dagger:hilt-android:2:36" to api helped, and now it is building.

**Comment by manuelvicnt** [comment]
Thanks! Check out the latest Hilt releases as the team has been working hard to remove the need for the `api`. `implementation` should work in the latest versions. Thanks!
