### ISSUE TITLE
HiltComponents_SingletonC not generated

### ISSUE THREAD

**Issue by victormpineda** [googlecodelabs/android-hilt#23]
After migrating mi project from dagger to Hilt (version 2.35), the code generated by Hilt is referencing a class that does not exists, so it cannot compile:

```
/Projects/android-app-users/app/build/generated/source/kapt/localhostDebug/com/example/android/Hilt_ExampleApp.java:20: error: cannot find symbol
      return DaggerExampleApp_HiltComponents_SingletonC.builder()
             ^
  symbol: variable DaggerExampleApp_HiltComponents_SingletonC
```

I've checked it in the build directory and the file does not exists. The rest of files generated by hilt seems ok. My application class is annotated with `@HiltAndroidApp`, but the code generated by hilt looks wrong.

**Comment by limitAlltheir** [comment]
I have same problem. How did u fix it?
