### ISSUE TITLE
Using deprecated API

### ISSUE THREAD

**Issue by grb0** [googlecodelabs/android-hilt#6]
Hilt is overriding deprecated `onAttach(Activity activity)` and calling `super.onAttach(activity)` in it, of all fragments annotated with @AndroidEntryPoint

I suppose this is something that should be remedied by Dagger since Hilt is build upon it or am I wrong?

**Comment by manuelvicnt** [comment]
Thanks for reporting this. We already fixed it: https://github.com/google/dagger/issues/2100

Thanks!
